### ISSUE TITLE
pod install fails

### ISSUE THREAD

**Issue by marcosanson** [ponnamkarthik/ext_video_player#3]
Hi guys,

anyone with this issue?

```
Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `ext_video_player` from `.symlinks/plugins/ext_video_player/ios`
    [!] No podspec found for `ext_video_player` in `.symlinks/plugins/ext_video_player/ios`
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/external_sources/path_source.rb:14:in `block in fetch'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/external_sources/path_source.rb:11:in `fetch'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:980:in `fetch_external_source'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:959:in `block (2 levels) in fetch_external_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:958:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:958:in `block in fetch_external_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:957:in `fetch_external_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:117:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:410:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:156:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'
```

**Comment by tanveer1302** [comment]
I am also facing the same issue while trying to run the app on iOS

-> Fetching podspec for `e2e` from `.symlinks/plugins/e2e/ios`
    -> Fetching podspec for `ext_video_player` from `.symlinks/plugins/ext_video_player/ios`
    [!] No podspec found for `ext_video_player` in `.symlinks/plugins/ext_video_player/ios`

I checked further into it and found of that the name of plugin is different in podspec than the actual name. Upon further googling, found this solution and it worked for me. 

https://github.com/CameronStuartSmith/flutter_lottie/issues/19#issuecomment-551112031

There are three steps mentioned in the solution and we need to perform first two only i.e., 

Path: ios/.symlinks/plugins/ext_video_player/ios/video_player.podspec

Follow the steps to fix:

1. Change the .podspec name in the path above to ext_video_player.podspec
2. Inside the .podspec, change the s.name value to ext_video_player

Happy coding :)

**Comment by Marchief84** [comment]
> I am also facing the same issue while trying to run the app on iOS
> 
> -> Fetching podspec for `e2e` from `.symlinks/plugins/e2e/ios`
> -> Fetching podspec for `ext_video_player` from `.symlinks/plugins/ext_video_player/ios`
> [!] No podspec found for `ext_video_player` in `.symlinks/plugins/ext_video_player/ios`
> 
> I checked further into it and found of that the name of plugin is different in podspec than the actual name. Upon further googling, found this solution and it worked for me.
> 
> [CameronStuartSmith/flutter_lottie#19 (comment)](https://github.com/CameronStuartSmith/flutter_lottie/issues/19#issuecomment-551112031)
> 
> There are three steps mentioned in the solution and we need to perform first two only i.e.,
> 
> Path: ios/.symlinks/plugins/ext_video_player/ios/video_player.podspec
> 
> Follow the steps to fix:
> 
> 1. Change the .podspec name in the path above to ext_video_player.podspec
> 2. Inside the .podspec, change the s.name value to ext_video_player
> 
> Happy coding :)

Thanks, this fixed it for me

**Comment by kh71** [comment]
yes work build and install but still error white screen


`objc[1007]: Class FLTFrameUpdater is implemented in both /private/var/containers/Bundle/Application/C146B863-072F-4CE5-B4E0-AF402ED86BF5/Runner.app/Frameworks/video_player.framework/video_player (0x1050b2f60) and /private/var/containers/Bundle/Application/C146B863-072F-4CE5-B4E0-AF402ED86BF5/Runner.app/Frameworks/ext_video_player.framework/ext_video_player (0x103036fb0). One of the two will be used. Which one is undefined.
objc[1007]: Class FLTVideoPlayer is implemented in both /private/var/containers/Bundle/Application/C146B863-072F-4CE5-B4E0-AF402ED86BF5/Runner.app/Frameworks/video_player.framework/video_player (0x1050b2f88) and /private/var/containers/Bundle/Application/C146B863-072F-4CE5-B4E0-AF402ED86BF5/Runner.app/Frameworks/ext_video_player.framework/ext_video_player (0x103036fd8). One of the two will be used. Which one is undefined.
objc[1007]: Class FLTVideoPlayerPlugin is implemented in both /private/var/containers/Bundle/Application/C146B863-072F-4CE5-B4E0-AF402ED86BF5/Runner.app/Frameworks/video_player.framework/video_player (0x1050b2fd8) and /private/var/containers/Bundle/Application/C146B863-072F-4CE5-B4E0-AF402ED86BF5/Runner.app/Frameworks/ext_video_player.framework/ext_video_player (0x103037028). One of the two will be used. Which one is undefined.
objc[1007]: Class FLTTextureMessage is implemented in both /private/var/containers/Bundle/Application/C146B863-072F-4CE5-B4E0-AF402ED86BF5/Runner.app/Frameworks/video_player.framework/video_player (0x1050b3028) and /private/var/containers/Bundle/Application/C146B863-072F-4CE5-B4E0-AF402ED86BF5/Runner.app/Frameworks/ext_video_player.framework/ext_video_player (0x103037078). One of the two will be used. Which one is undefined.
objc[1007]: Class FLTCreateMessage is implemented in both /private/var/containers/Bundle/Application/C146B863-072F-4CE5-B4E0-AF402ED86BF5/Runner.app/Frameworks/video_player.framework/video_player (0x1050b3078) and /private/var/containers/Bundle/Application/C146B863-072F-4CE5-B4E0-AF402ED86BF5/Runner.app/Frameworks/ext_video_player.framework/ext_video_player (0x1030370c8). One of the two will be used. Which one is undefined.
objc[1007]: Class FLTLoopingMessage is implemented in both /private/var/containers/Bundle/Application/C146B863-072F-4CE5-B4E0-AF402ED86BF5/Runner.app/Frameworks/video_player.framework/video_player (0x1050b30c8) and /private/var/containers/Bundle/Application/C146B863-072F-4CE5-B4E0-AF402ED86BF5/Runner.app/Frameworks/ext_video_player.framework/ext_video_player (0x103037118). One of the two will be used. Which one is undefined.
objc[1007]: Class FLTVolumeMessage is implemented in both /private/var/containers/Bundle/Application/C146B863-072F-4CE5-B4E0-AF402ED86BF5/Runner.app/Frameworks/video_player.framework/video_player (0x1050b3118) and /private/var/containers/Bundle/Application/C146B863-072F-4CE5-B4E0-AF402ED86BF5/Runner.app/Frameworks/ext_video_player.framework/ext_video_player (0x103037168). One of the two will be used. Which one is undefined.
objc[1007]: Class FLTPositionMessage is implemented in both /private/var/containers/Bundle/Application/C146B863-072F-4CE5-B4E0-AF402ED86BF5/Runner.app/Frameworks/video_player.framework/video_player (0x1050b3168) and /private/var/containers/Bundle/Application/C146B863-072F-4CE5-B4E0-AF402ED86BF5/Runner.app/Frameworks/ext_video_player.framework/ext_video_player (0x1030371b8). One of the two will be used. Which one is undefined.
2020-08-26 17:09:43.176155+0700 Runner[1007:127107] Metal API Validation Enabled
2020-08-26 17:09:43.420805+0700 Runner[1007:127107] Could not load the "LaunchImage" image referenced from a nib in the bundle with identifier "com.kh71.sport"
2020-08-26 17:09:43.553101+0700 Runner[1007:127107] *** Assertion failure in -[FlutterEngine registrarForPlugin:], ../../flutter/shell/platform/darwin/ios/framework/Source/FlutterEngine.mm:725
2020-08-26 17:09:43.555518+0700 Runner[1007:127107] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Duplicate plugin key: FLTVideoPlayerPlugin'
*** First throw call stack:
(0x1affc5654 0x1afce7bcc 0x1afec86ec 0x1b030e16c 0x1031b49f4 0x102de8354 0x102de8544 0x102de88a0 0x1b406fc14 0x1b40719a0 0x1b407723c 0x1b381ba2c 0x1b3ccc1e8 0x1b381c510 0x1b381bf64 0x1b381c33c 0x1b381bbfc 0x1b3820098 0x1b3bf02ac 0x1b3ce562c 0x1b381fdf4 0x1b3ce5528 0x1b381fc5c 0x1b368fe30 0x1b368e9d0 0x1b368fb68 0x1b4075488 0x1b3c15598 0x1b514c61c 0x1b5171194 0x1b5156bfc 0x1b5170e50 0x1050fb730 0x1050febb0 0x1b5195850 0x1b519551c 0x1b5195a44 0x1aff43ad8 0x1aff43a30 0x1aff431b8 0x1aff3e1e8 0x1aff3dba8 0x1ba0ad344 0x1b40793e4 0x102de8a94 0x1afdc58f0)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) `

**Comment by workerbee22** [comment]
Yep `pod install` get:

`[!] No podspec found for ext_video_player in .symlinks/plugins/ext_video_player/ios`
